// <auto-generated />
using System;
using AdresaService.Entities.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdresaService.Migrations
{
    [DbContext(typeof(AdresaContext))]
    partial class AdresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdresaService.Entities.Adresa", b =>
                {
                    b.Property<Guid>("AdresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DrzavaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresaId");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Adrese");

                    b.HasData(
                        new
                        {
                            AdresaId = new Guid("1c989ee3-13b2-4d3b-abeb-c4e6343eace7"),
                            Broj = "1",
                            DrzavaId = new Guid("f320743f-6c87-47ca-9f82-50191c1d31ac"),
                            Mesto = "Novi Sad",
                            PostanskiBroj = "21000",
                            Ulica = "Branka Ilica"
                        },
                        new
                        {
                            AdresaId = new Guid("37371ef6-4f25-48b3-9bf2-fe72a81f88d2"),
                            Broj = "23",
                            DrzavaId = new Guid("9ce21ce2-7809-4e28-ba74-fd2f1bc6466a"),
                            Mesto = "Bijeljna",
                            PostanskiBroj = "76300",
                            Ulica = "Solunska"
                        });
                });

            modelBuilder.Entity("AdresaService.Entities.Drzava", b =>
                {
                    b.Property<Guid>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDrzave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzave");

                    b.HasData(
                        new
                        {
                            DrzavaId = new Guid("f320743f-6c87-47ca-9f82-50191c1d31ac"),
                            NazivDrzave = "Srbija"
                        },
                        new
                        {
                            DrzavaId = new Guid("9ce21ce2-7809-4e28-ba74-fd2f1bc6466a"),
                            NazivDrzave = "Bosna i hercegovina"
                        });
                });

            modelBuilder.Entity("AdresaService.Entities.Adresa", b =>
                {
                    b.HasOne("AdresaService.Entities.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });
#pragma warning restore 612, 618
        }
    }
}
