// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvlascenoLiceService.Entities.DataContext;

namespace OvlascenoLiceService.Migrations
{
    [DbContext(typeof(OvlascenoLiceContext))]
    [Migration("20220207153338_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OvlascenoLiceService.Entities.BrojTable", b =>
                {
                    b.Property<Guid>("BrojTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OvlascenoLiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OznakaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RbTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BrojTableId");

                    b.HasIndex("OvlascenoLiceId");

                    b.ToTable("BrojTable");

                    b.HasData(
                        new
                        {
                            BrojTableId = new Guid("f7837323-afeb-4aa9-ba28-cd0912bb1fac"),
                            OvlascenoLiceId = new Guid("e22f999d-5c61-4dce-965b-9c6667efc74d"),
                            OznakaTable = "Talba3"
                        },
                        new
                        {
                            BrojTableId = new Guid("97a9c3ec-6af3-4b02-ad18-097702f62fa0"),
                            OvlascenoLiceId = new Guid("e22f999d-5c61-4dce-965b-9c6667efc74d"),
                            OznakaTable = "Tabla12"
                        },
                        new
                        {
                            BrojTableId = new Guid("33dbd6be-207b-43a5-ab4f-65aa47c6ee3c"),
                            OvlascenoLiceId = new Guid("5e1bfffc-1aee-4662-bc04-341c35b9ebdc"),
                            OznakaTable = "Tabla25"
                        });
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.OvlascenoLice", b =>
                {
                    b.Property<Guid>("OvlascenoLiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojPasosa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DrzavaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OvlascenoLiceId");

                    b.ToTable("OvlascenoLice");

                    b.HasData(
                        new
                        {
                            OvlascenoLiceId = new Guid("5ed44cab-255d-4bb7-9cc9-828ec90bfaf5"),
                            AdresaId = new Guid("1c989ee3-13b2-4d3b-abeb-c4e6343eace7"),
                            Ime = "Petar",
                            JMBG = "1002987800035",
                            Prezime = "Petrovic"
                        },
                        new
                        {
                            OvlascenoLiceId = new Guid("5e1bfffc-1aee-4662-bc04-341c35b9ebdc"),
                            AdresaId = new Guid("37371ef6-4f25-48b3-9bf2-fe72a81f88d2"),
                            Ime = "Marko",
                            JMBG = "2004983800022",
                            Prezime = "Markovic"
                        },
                        new
                        {
                            OvlascenoLiceId = new Guid("e22f999d-5c61-4dce-965b-9c6667efc74d"),
                            BrojPasosa = "0252624",
                            DrzavaId = new Guid("9ce21ce2-7809-4e28-ba74-fd2f1bc6466a"),
                            Ime = "Nemanja",
                            Prezime = "Nenic"
                        });
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.BrojTable", b =>
                {
                    b.HasOne("OvlascenoLiceService.Entities.OvlascenoLice", "OvlascenoLice")
                        .WithMany("BrojeviTabli")
                        .HasForeignKey("OvlascenoLiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OvlascenoLice");
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.OvlascenoLice", b =>
                {
                    b.Navigation("BrojeviTabli");
                });
#pragma warning restore 612, 618
        }
    }
}
