// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelaService.Entities.DataContext;

namespace ParcelaService.Migrations
{
    [DbContext(typeof(ParcelaContext))]
    partial class ParcelaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParcelaService.Entities.Klasa", b =>
                {
                    b.Property<Guid>("ID_Klasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KlasaNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Klasa");

                    b.ToTable("Klasa");

                    b.HasData(
                        new
                        {
                            ID_Klasa = new Guid("f39c9623-c6b6-48cb-b4dd-0340c7431870"),
                            KlasaNaziv = "Prva"
                        },
                        new
                        {
                            ID_Klasa = new Guid("0ec59e12-b271-471f-9a13-5c9c8ed0eda7"),
                            KlasaNaziv = "Druga"
                        },
                        new
                        {
                            ID_Klasa = new Guid("e496b563-abb9-48a9-8972-800f41a4a3a1"),
                            KlasaNaziv = "Treca"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
