// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZalbaService.Entities.DataContext;

namespace ZalbaService.Migrations
{
    [DbContext(typeof(ZalbaContext))]
    [Migration("20220115144706_StatusTipRadnjaEntities")]
    partial class StatusTipRadnjaEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZalbaService.Entities.RadnjaZaZalbu", b =>
                {
                    b.Property<Guid>("RadnjaZaZalbuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivRadnjeZaZalbu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RadnjaZaZalbuId");

                    b.ToTable("RadnjaZaZalbu");

                    b.HasData(
                        new
                        {
                            RadnjaZaZalbuId = new Guid("0c9f2e15-4271-408d-8d40-e0cf57b33285"),
                            NazivRadnjeZaZalbu = "JN ide u drugi krug sa novim uslovima"
                        },
                        new
                        {
                            RadnjaZaZalbuId = new Guid("6ac4f54a-d8f4-4d67-9b53-b97e240cbfb9"),
                            NazivRadnjeZaZalbu = "JN ide u drugi krug sa starim uslovima"
                        },
                        new
                        {
                            RadnjaZaZalbuId = new Guid("4688f1f3-e7cf-4772-b1a4-1ac19fadef00"),
                            NazivRadnjeZaZalbu = "JN ne ide u drugi krug"
                        });
                });

            modelBuilder.Entity("ZalbaService.Entities.StatusZalbe", b =>
                {
                    b.Property<Guid>("StatusZalbeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivStatusaZalbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusZalbeId");

                    b.ToTable("StatusZalbe");

                    b.HasData(
                        new
                        {
                            StatusZalbeId = new Guid("646f2074-e10e-4078-be21-403d6ac873c7"),
                            NazivStatusaZalbe = "Usvojena"
                        },
                        new
                        {
                            StatusZalbeId = new Guid("c677ec37-647f-421a-b68d-df8ef37b7edc"),
                            NazivStatusaZalbe = "Odbijena"
                        },
                        new
                        {
                            StatusZalbeId = new Guid("083df6f6-200e-45fd-be27-2b88cb8ee7b3"),
                            NazivStatusaZalbe = "Otvorena"
                        });
                });

            modelBuilder.Entity("ZalbaService.Entities.TipZalbe", b =>
                {
                    b.Property<Guid>("TipZalbeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipaZalbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipZalbeId");

                    b.ToTable("TipZalbe");

                    b.HasData(
                        new
                        {
                            TipZalbeId = new Guid("01c0db0a-6906-4f21-8d40-efe95e0748a0"),
                            NazivTipaZalbe = "Zalba na tok javnog nadmetanja"
                        },
                        new
                        {
                            TipZalbeId = new Guid("a1168e04-72f5-4ad8-9441-e1edcb533406"),
                            NazivTipaZalbe = "Zalba na Odluku o davanju u zakup"
                        },
                        new
                        {
                            TipZalbeId = new Guid("7bac6453-dac7-4192-a5de-ffe48dd1501c"),
                            NazivTipaZalbe = "Zalba na Odluku o davanju na koriscenje"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
