// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZalbaService.Entities.DataContext;

namespace ZalbaService.Migrations
{
    [DbContext(typeof(ZalbaContext))]
    [Migration("20220113000555_StatusZalbeEntity")]
    partial class StatusZalbeEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZalbaService.Entities.StatusZalbe", b =>
                {
                    b.Property<Guid>("StatusZalbeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivStatusaZalbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusZalbeId");

                    b.ToTable("StatusZalbe");

                    b.HasData(
                        new
                        {
                            StatusZalbeId = new Guid("7d1878b3-b31d-46a3-91a8-a2bbc833eda4"),
                            NazivStatusaZalbe = "Usvojena"
                        },
                        new
                        {
                            StatusZalbeId = new Guid("2ccd78ba-8383-4f92-9c15-06d0373d65dd"),
                            NazivStatusaZalbe = "Odbijena"
                        },
                        new
                        {
                            StatusZalbeId = new Guid("dba4f831-20c2-418a-a5fb-da69aa8588bb"),
                            NazivStatusaZalbe = "Otvorena"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
