// <auto-generated />
using System;
using DokumentService.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DokumentService.Migrations
{
    [DbContext(typeof(DokumentDbContext))]
    [Migration("20220207181435_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DokumentService.Entities.Dokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TipDokumentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipDokumentaId");

                    b.HasIndex("ZavodniBroj")
                        .IsUnique();

                    b.ToTable("Dokument");

                    b.HasData(
                        new
                        {
                            Id = new Guid("854a5603-31c6-4815-b393-a2b61887ba5e"),
                            Datum = new DateTime(2022, 2, 7, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(3207),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 10, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(3882),
                            TipDokumentaId = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            ZavodniBroj = "PSPG-1/2022"
                        },
                        new
                        {
                            Id = new Guid("13b6c9df-03b9-4313-af6a-6c2e076e8a0a"),
                            Datum = new DateTime(2022, 2, 7, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(5100),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 10, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(5106),
                            TipDokumentaId = new Guid("3e649b2d-5569-4463-80f3-04382ef4a7eb"),
                            ZavodniBroj = "IJEN-1/2022"
                        },
                        new
                        {
                            Id = new Guid("7147fd52-b938-4cec-8b81-dfa51f123f0c"),
                            Datum = new DateTime(2022, 2, 7, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(5126),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 10, 19, 14, 35, 236, DateTimeKind.Local).AddTicks(5130),
                            TipDokumentaId = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            ZavodniBroj = "PSPG-2/2022"
                        });
                });

            modelBuilder.Entity("DokumentService.Entities.TipDokumenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NazivTipa")
                        .IsUnique();

                    b.ToTable("TipDokumenta");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            NazivTipa = "Potvrda o statusu poljoprivrednog gazdinstava u registru poljoprivrednih gazdinstava"
                        },
                        new
                        {
                            Id = new Guid("3e649b2d-5569-4463-80f3-04382ef4a7eb"),
                            NazivTipa = "Izvod iz javne evidencije o nepokretnosti"
                        });
                });

            modelBuilder.Entity("DokumentService.Entities.Dokument", b =>
                {
                    b.HasOne("DokumentService.Entities.TipDokumenta", "TipDokumenta")
                        .WithMany()
                        .HasForeignKey("TipDokumentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipDokumenta");
                });
#pragma warning restore 612, 618
        }
    }
}
