// <auto-generated />
using System;
using DokumentService.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DokumentService.Migrations
{
    [DbContext(typeof(DokumentDbContext))]
    [Migration("20220202141649_SeedDb")]
    partial class SeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentService.Entities.Dokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TipDokumentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipDokumentaId");

                    b.ToTable("Dokument");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4bcdc43-e7ed-4364-90b1-fa5f84e666f3"),
                            Datum = new DateTime(2022, 2, 2, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(6641),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 5, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7037),
                            TipDokumentaId = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            ZavodniBroj = "PSPG-1/2022"
                        },
                        new
                        {
                            Id = new Guid("b2f3c1aa-4855-4fd7-bf17-0824280acada"),
                            Datum = new DateTime(2022, 2, 2, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7736),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 5, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7738),
                            TipDokumentaId = new Guid("3e649b2d-5569-4463-80f3-04382ef4a7eb"),
                            ZavodniBroj = "IJEN-1/2022"
                        },
                        new
                        {
                            Id = new Guid("ce0244e0-e7be-40c3-b558-bcebcf7b2466"),
                            Datum = new DateTime(2022, 2, 2, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7753),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 5, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7756),
                            TipDokumentaId = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            ZavodniBroj = "PSPG-2/2022"
                        },
                        new
                        {
                            Id = new Guid("a2fa2d1e-ed38-4b63-b0c2-41fb70eaadc5"),
                            Datum = new DateTime(2022, 2, 2, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7776),
                            DatumDonosenjaDokumenta = new DateTime(2022, 2, 5, 15, 16, 48, 584, DateTimeKind.Local).AddTicks(7778),
                            TipDokumentaId = new Guid("3e649b2d-5569-4463-80f3-04382ef4a7eb"),
                            ZavodniBroj = "IJEN-2/2022"
                        });
                });

            modelBuilder.Entity("DocumentService.Entities.TipDokumenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipDokumenta");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77cbe573-4ad7-4db8-b9b1-7a9f45bec5db"),
                            NazivTipa = "Potvrda o statusu poljoprivrednog gazdinstava u registru poljoprivrednih gazdinstava"
                        },
                        new
                        {
                            Id = new Guid("3e649b2d-5569-4463-80f3-04382ef4a7eb"),
                            NazivTipa = "Izvod iz javne evidencije o nepokretnosti"
                        });
                });

            modelBuilder.Entity("DocumentService.Entities.Dokument", b =>
                {
                    b.HasOne("DocumentService.Entities.TipDokumenta", "TipDokumenta")
                        .WithMany()
                        .HasForeignKey("TipDokumentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipDokumenta");
                });
#pragma warning restore 612, 618
        }
    }
}
